Fix "method_lines" issue in CreateUserController.php
Reconmap/api-backend pull request #11
Opened 2020-10-01 23:23 UTC by AbderrahimSoubaiElidrissi

2020-10-02 07:11 UTC, santiagolizardo commented on src/Controllers/Users/CreateUserController.php
> +            $result = $this->container->get(Redis::class)->lPush("email:queue",
The comment (var Redis) should have been removed as well as the result variable not longer holds a Redis instance.

2020-10-02 07:12 UTC, santiagolizardo requested changes
Thanks for your PR @AbderrahimSoubaiElidrissi . Unfortunately the change you are suggesting is not a great improvement over existing code.
If you want to make a difference to this class why don't you extract all the code that make the push to Redis to a new method on the same class to have two smaller methods instead of a single big one?
Thanks!

2020-10-02 17:29 UTC, closed without merging

2020-10-02 17:29 UTC, santiagolizardo commented
Closing due to the inactivity

2020-10-03 15:42 UTC, wr4 commented
This type of spam people making PRs just to win a t shirt, thanks to DO update this PRs like this will not be counted to this dude, "Talk is cheap. Show me the code".